---
- name: Power VSI Creation Demo
  hosts: localhost
  collections:
    ibm.cloudcollection
  vars:
    pi_name: ansible-demo-power-vm
    sys_type: s922
    pi_image: "YOUR IMAGE NAME HERE"
    proc_type: shared
    processors: "0.25"
    memory: "2"
    network_name: ansible-demo-network
    pi_cloud_instance_id: "YOUR POWERVS SERVICE ID HERE"
    ssh_public_key_name: "YOUR SSH KEY NAME HERE" 
    ssh_public_key: "YOUR SSH KEY HERE"

  tasks:
  - name: SSH Key configuration
    block:
      - name: Check for existing SSH Key
        ibm_pi_key_info:
          pi_key_name: "{{ ssh_public_key_name }}"
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"

    rescue:
      - name: Add new SSH Key
        ibm_pi_key:
          pi_key_name: "{{ ssh_public_key_name }}"
          pi_ssh_key: "{{ ssh_public_key }}"
          state: available
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"

  - name: Network configuration
    block:
      - name: Check for existing network
        ibm_pi_network_info:
          pi_network_name: "{{ network_name }}"
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"

    rescue:
      - name: Create new network
        ibm_pi_network:
          pi_network_type: vlan
          pi_network_name: "{{ network_name }}"
          pi_cidr: 10.20.30.0/24
          state: available
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"

  - name: Retrieve image info
    ibm_pi_image_info:
      pi_image_name: "{{ pi_image }}"
      pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
    register: image_info

  - name: Set VM image name/id dictionary fact
    set_fact: pvs_image="{{ image_info.resource.id }}"


  - name: Create PVS LPAR
    block:
      - name: Check Virtual Server Instance doesn't exist
        ibm_pi_instance_info:
          pi_instance_name: "{{ pi_name }}"
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"

      - debug:
          msg: "Instance name already taken. Please choose another pi_name"

    rescue:
      - name: Create a POWER Virtual Server Instance
        ibm_pi_instance:
          pi_key_pair_name: "{{ ssh_public_key_name }}"
          pi_instance_name: "{{ pi_name }}"
          pi_network:
            - network_id: "{{ network_name }}"
          pi_proc_type: "{{ proc_type }}"
          pi_image_id: "{{ pvs_image }}"
          pi_memory: "{{ memory }}"
          pi_sys_type: "{{ sys_type }}"
          pi_processors: "{{ processors }}"
          state: available
          pi_cloud_instance_id: "{{ pi_cloud_instance_id }}"
